server:
  port: 18002

spring:
  application:
    name: demo-application # 应用名
  cloud:
    nacos:
      # Nacos 作为注册中心的配置项，对应 NacosDiscoveryProperties 配置类
      discovery:
        server-addr: guangjian.top:18048 # Nacos 服务器地址

grpc:
  # gRPC 服务器配置，对应 GrpcServerProperties 配置类
  server:
    port: 18009 # gRPC Server 随机端口
